### ISSUE TITLE
Crash when Druid gets hit

### ISSUE THREAD

**Issue by EmSalce** [Clark919/ExpandedClasses#3]
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1297.method_5643(net.minecraft.class_1282, float)" because "entity" is null
	at io.github.apace100.apoli.power.factory.action.EntityActions.lambda$register$1(EntityActions.java:70)
	at io.github.apace100.apoli.power.factory.action.ActionFactory$Instance.accept(ActionFactory.java:41)
	at io.github.apace100.apoli.power.factory.action.BiEntityActions.lambda$register$2(BiEntityActions.java:47)
	at io.github.apace100.apoli.power.factory.action.ActionFactory$Instance.accept(ActionFactory.java:41)
	at io.github.apace100.apoli.power.factory.action.meta.AndAction.lambda$action$0(AndAction.java:14)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at io.github.apace100.apoli.power.factory.action.meta.AndAction.action(AndAction.java:14)
	at io.github.apace100.apoli.power.factory.action.ActionFactory$Instance.accept(ActionFactory.java:41)
	at io.github.apace100.apoli.power.factory.action.meta.ChanceAction.action(ChanceAction.java:16)
	at io.github.apace100.apoli.power.factory.action.ActionFactory$Instance.accept(ActionFactory.java:41)
	at io.github.apace100.apoli.power.ModifyDamageTakenPower.executeActions(ModifyDamageTakenPower.java:87)
	at net.minecraft.class_1309.md053716$lambda$modifyDamageTaken$10$19(class_1309.java:8775)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.LinkedList$LLSpliterator.forEachRemaining(LinkedList.java:1242)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at io.github.apace100.apoli.component.PowerHolderComponent.modify(PowerHolderComponent.java:156)
	at io.github.apace100.apoli.component.PowerHolderComponent.modify(PowerHolderComponent.java:141)
	at net.minecraft.class_1309.localvar$zlk000$modifyDamageTaken(class_1309.java:8774)
	at net.minecraft.class_1309.method_5643(class_1309.java)
	at net.minecraft.class_1657.method_5643(class_1657.java:952)
	at net.minecraft.class_3222.method_5643(class_3222.java:713)
	at org.betterx.betternether.entity.EntitySkull.method_5694(EntitySkull.java:109)
	at net.minecraft.class_1657.method_7341(class_1657.java:631)
	at net.minecraft.class_1657.method_6007(class_1657.java:604)
	at net.minecraft.class_1309.method_5773(class_1309.java:2385)
	at net.minecraft.class_1657.method_5773(class_1657.java:284)
	at net.minecraft.class_3222.method_14226(class_3222.java:487)
	at net.minecraft.class_3244.method_18784(class_3244.java:268)
	at net.minecraft.class_2535.method_10754(class_2535.java:248)
	at net.minecraft.class_3242.method_14357(class_3242.java:183)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:886)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819)
	at net.minecraft.class_1132.method_3748(class_1132.java:98)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:665)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.base/java.lang.Thread.run(Thread.java:833)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at io.github.apace100.apoli.power.factory.action.EntityActions.lambda$register$1(EntityActions.java:70)
	at io.github.apace100.apoli.power.factory.action.ActionFactory$Instance.accept(ActionFactory.java:41)
	at io.github.apace100.apoli.power.factory.action.BiEntityActions.lambda$register$2(BiEntityActions.java:47)
	at io.github.apace100.apoli.power.factory.action.ActionFactory$Instance.accept(ActionFactory.java:41)
	at io.github.apace100.apoli.power.factory.action.meta.AndAction.lambda$action$0(AndAction.java:14)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at io.github.apace100.apoli.power.factory.action.meta.AndAction.action(AndAction.java:14)
	at io.github.apace100.apoli.power.factory.action.ActionFactory$Instance.accept(ActionFactory.java:41)
	at io.github.apace100.apoli.power.factory.action.meta.ChanceAction.action(ChanceAction.java:16)
	at io.github.apace100.apoli.power.factory.action.ActionFactory$Instance.accept(ActionFactory.java:41)
	at io.github.apace100.apoli.power.ModifyDamageTakenPower.executeActions(ModifyDamageTakenPower.java:87)
	at net.minecraft.class_1309.md053716$lambda$modifyDamageTaken$10$19(class_1309.java:8775)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.LinkedList$LLSpliterator.forEachRemaining(LinkedList.java:1242)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at io.github.apace100.apoli.component.PowerHolderComponent.modify(PowerHolderComponent.java:156)
	at io.github.apace100.apoli.component.PowerHolderComponent.modify(PowerHolderComponent.java:141)
	at net.minecraft.class_1309.localvar$zlk000$modifyDamageTaken(class_1309.java:8774)
	at net.minecraft.class_1309.method_5643(class_1309.java)
	at net.minecraft.class_1657.method_5643(class_1657.java:952)
	at net.minecraft.class_3222.method_5643(class_3222.java:713)
	at org.betterx.betternether.entity.EntitySkull.method_5694(EntitySkull.java:109)
	at net.minecraft.class_1657.method_7341(class_1657.java:631)
	at net.minecraft.class_1657.method_6007(class_1657.java:604)
	at net.minecraft.class_1309.method_5773(class_1309.java:2385)
	at net.minecraft.class_1657.method_5773(class_1657.java:284)

-- Player being ticked --
Details:
	Entity Type: minecraft:player (net.minecraft.class_3222)
	Entity ID: 244
	Entity Name: Xellik
	Entity's Exact location: 2.92, 62.00, 5.50
	Entity's Block location: World: (2,62,5), Section: (at 2,14,5 in 0,3,0; chunk contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at net.minecraft.class_3222.method_14226(class_3222.java:487)
	at net.minecraft.class_3244.method_18784(class_3244.java:268)
	at net.minecraft.class_2535.method_10754(class_2535.java:248)
	at net.minecraft.class_3242.method_14357(class_3242.java:183)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:886)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819)
	at net.minecraft.class_1132.method_3748(class_1132.java:98)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:665)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by Clark919** [comment]
Thanks for the report. Does this occur with any mob other than the Skull from Better Nether (as it seems this caused the crash from a brief look at the log).

**Comment by EmSalce** [comment]
Yeah, taking frostbite damage causes the same thing.

One of the origins we use causes a player to 'freeze' at night if not wearing a leather chestpiece(Animal Origins), and when he took damage it caused a tick crash as well. Had to delete his player data but luckily it was early enough he didnt lose much

**Comment by Clark919** [comment]
Right, I'll look into what specifically is causing this when I have some free time. If I can't determine what is causing this or am unable to fix it I'll adjust how the Druid works most likely.

**Comment by Clark919** [comment]
I've identified the issue as the power trying to inflict thorns damage to a non-living damage source. This will be fixed in the next patch. If you encounter the problem again after the update, feel free to submit another issue.
